ALTER TABLE ai_usage ADD COLUMN cache_read INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN cache_write INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN requests INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_usage ADD COLUMN payload_chars INTEGER NOT NULL DEFAULT 0;
INSERT INTO schema_migrations(version) VALUES(6);
PRAGMA user_version=6;
