import { AboutLinks } from './about';
import { useEffect,useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { request } from './api';
import { Modal } from './connections';
import { AnswerMarkdown } from './markdown';
import type { Document } from './types';

type PresentationNote={id:string;title:string;body_md:string;block_id:string|null};
export type UpdateInfo={configured:boolean;available?:boolean;version?:string;current_version:string;body?:string};
export async function saveExport(docId:string,format:string){return invoke<string|null>('export_document',{docId,format});}
export function DocumentActions({doc}:{doc:Document}){
  const [exporting,setExporting]=useState(false);const [notes,setNotes]=useState(false);
  return <><div className="document-actions"><button onClick={()=>setExporting(true)}>내보내기</button><button onClick={()=>setNotes(true)}>발표 노트</button>{doc.source_kind==='arxiv_html'&&<span>arXiv HTML 원문 · 표·LaTeX 수식 보존</span>}</div>{exporting&&<ExportDialog doc={doc} onClose={()=>setExporting(false)}/>} {notes&&<PresentationDialog doc={doc} onClose={()=>setNotes(false)}/>}</>;
}
function ExportDialog({doc,onClose}:{doc:Document;onClose:()=>void}){
  const [format,setFormat]=useState('html');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  return <Modal title="논문 내보내기" onClose={onClose}><div className="dialog-content"><p>이 PC에 저장된 원문·번역·주석을 내보냅니다. AI 호출은 없습니다.</p><label>파일 형식<select value={format} onChange={e=>setFormat(e.target.value)}><option value="html">단일 HTML · 오프라인 리더</option><option value="md">Markdown 대역본</option><option value="presentation">발표 노트 Markdown</option></select></label><p>{format==='html'?'표·수식·글꼴·그림이 파일 하나에 포함됩니다. 보기 모드, 검색, 목차와 다크모드를 사용할 수 있습니다.':format==='md'?'원문과 번역을 함께 저장합니다. 병합 표는 HTML 표, 그림은 내장 이미지로 포함됩니다.':'모아 둔 발표 노트를 현재 순서대로 저장합니다.'}</p><small>내보내기·공유 시 논문 원문의 저작권과 이용 조건을 확인해 주세요.</small><button className="primary-button" disabled={busy} onClick={()=>{setBusy(true);setMessage('');void saveExport(doc.id,format).then(path=>setMessage(path?`저장했습니다: ${path}`:'저장을 취소했습니다.')).catch(e=>setMessage(String(e))).finally(()=>setBusy(false));}}>{busy?'파일을 준비하고 있습니다…':'저장 위치 선택'}</button>{message&&<p role="status" className="path-text">{message}</p>}</div></Modal>;
}
function PresentationDialog({doc,onClose}:{doc:Document;onClose:()=>void}){
  const [notes,setNotes]=useState<PresentationNote[]>([]);const [selected,setSelected]=useState<string|null>(null);const [title,setTitle]=useState('');const [body,setBody]=useState('');const [block,setBlock]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const base=`/documents/${doc.id}/presentation`;
  const refresh=()=>request<PresentationNote[]>(base).then(setNotes);
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[doc.id]);
  const choose=(n:PresentationNote)=>{setSelected(n.id);setTitle(n.title);setBody(n.body_md);};
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const move=(index:number,delta:number)=>{const ids=notes.map(n=>n.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void run(()=>request(base+'/order',{method:'PUT',body:JSON.stringify({ids})}));};
  return <Modal title="발표 노트" onClose={onClose}><div className="dialog-content presentation"><p>AI 답변의 ‘발표 노트에 추가’로 모으거나 직접 작성하세요. 원문 근거를 확인하며 발표 흐름을 정리할 수 있습니다.</p><div className="presentation-list">{notes.map((n,i)=><div key={n.id}><button className={selected===n.id?'selected':''} onClick={()=>choose(n)}>{i+1}. {n.title}</button><button disabled={busy||i===0} aria-label={`${n.title} 위로`} onClick={()=>move(i,-1)}>↑</button><button disabled={busy||i===notes.length-1} aria-label={`${n.title} 아래로`} onClick={()=>move(i,1)}>↓</button><button disabled={busy} aria-label={`${n.title} 삭제`} onClick={()=>void run(async()=>{await request(base+'/'+n.id,{method:'DELETE'});if(selected===n.id){setSelected(null);setTitle('');setBody('');}})}>삭제</button>{n.block_id&&<small>근거: {n.block_id}</small>}</div>)}</div><div className="presentation-add"><label>논문 블록에서 가져오기<select value={block} onChange={e=>setBlock(e.target.value)}><option value="">블록 선택</option>{doc.blocks.map(b=><option key={b.id} value={b.id}>{b.n||b.id} · {(b.note?.title||b.ko||b.caption_ko||b.en||b.caption_en||b.latex||'').replace(/<[^>]*>/g,'').slice(0,70)}</option>)}</select></label><button disabled={!block||busy} onClick={()=>void run(async()=>{const note=await request<PresentationNote>(base,{method:'POST',body:JSON.stringify({block_id:block,title:doc.blocks.find(b=>b.id===block)?.n||'논문 메모'})});choose(note);})}>블록 추가</button></div><button onClick={()=>{setSelected(null);setTitle('');setBody('');}}>새 메모 작성</button><label>메모 제목<input value={title} maxLength={300} onChange={e=>setTitle(e.target.value)}/></label><label>발표 내용<textarea rows={7} value={body} maxLength={30000} onChange={e=>setBody(e.target.value)}/></label><details><summary>내용 미리보기</summary><AnswerMarkdown text={body}/></details><div className="dialog-actions"><button disabled={!title.trim()||!body.trim()||busy} className="primary-button" onClick={()=>void run(async()=>{const result=await request<PresentationNote|undefined>(base+(selected?'/'+selected:''),{method:selected?'PUT':'POST',body:JSON.stringify({title,body_md:body})});if(result)choose(result);})}>메모 저장</button><button disabled={!notes.length||busy} onClick={()=>void run(()=>saveExport(doc.id,'presentation'))}>발표 노트 내보내기</button></div>{error&&<p role="alert">{error}</p>}</div></Modal>;
}

export function AppSettings({onClose,initialUpdate}:{onClose:()=>void;initialUpdate?:UpdateInfo}){
  const [storage,setStorage]=useState<{path:string;busy:boolean}|null>(null);const [target,setTarget]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [update,setUpdate]=useState<UpdateInfo|null>(initialUpdate??null);const [automatic,setAutomatic]=useState(localStorage.getItem('paperduet-auto-update')!=='false');
  useEffect(()=>{void request<{path:string;busy:boolean}>('/settings/storage').then(setStorage).catch(e=>setStatus(e.message));void invoke<UpdateInfo>('update_status').then(status=>setUpdate(known=>known?.available?known:status)).catch(e=>setStatus(String(e)));},[]);
  const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setStatus('');try{await fn();}catch(e){setStatus(String(e));}finally{setBusy(false);}};
  return <Modal title="앱 설정" onClose={onClose}><div className="dialog-content"><h3>저장 위치</h3><p className="path-text">{storage?.path||'확인 중…'}</p><p>논문·번역·대화·발표 노트를 빈 폴더에 복사하고 검증한 뒤 앱을 재시작합니다. 기존 폴더는 보관됩니다. API 키는 Windows 자격 증명 관리자에 그대로 유지됩니다.</p><button className="secondary-button" disabled={busy} onClick={()=>void action(async()=>{const path=await invoke<string|null>('choose_storage');if(path)setTarget(path);})}>새 저장 폴더 선택</button>{target&&<><p className="path-text">새 위치: {target}</p><button disabled={busy} className="primary-button" onClick={()=>void action(async()=>{setStatus('복사·검증 중입니다. 완료되면 재시작합니다.');await invoke('migrate_storage',{path:target});})}>복사·검증 후 재시작</button></>}<small>번역이나 질문이 진행 중이면 끝내거나 중지한 뒤 변경하세요.</small><hr/><h3>업데이트</h3><p>현재 버전 {update?.current_version||'…'}</p><label><input type="checkbox" checked={automatic} onChange={e=>{setAutomatic(e.target.checked);localStorage.setItem('paperduet-auto-update',String(e.target.checked));}}/> 시작할 때 새 버전 확인</label>{update&&!update.configured?<p>이 로컬 빌드는 업데이트 배포 경로가 연결되지 않았습니다. 새 설치 파일로 업데이트할 수 있습니다.</p>:<><button className="secondary-button" disabled={busy} onClick={()=>void action(async()=>{const result=await invoke<UpdateInfo>('check_update');setUpdate(result);setStatus(result.available?'새 버전이 있습니다.':'현재 최신 버전입니다.');})}>새 버전 확인</button>{update?.available&&<><p>새 버전 {update.version}</p><pre className="update-notes">{update.body}</pre><button disabled={busy} onClick={()=>void action(()=>invoke('install_update'))}>다운로드·검증 후 설치</button><small>서명을 확인한 뒤 앱을 닫고 설치합니다.</small></>}</>}{status&&<p role="status" className="path-text">{status}</p>}<hr/><AboutLinks/></div></Modal>;
}

export function ArxivInput({onImported}:{onImported:(id:string)=>void}){
  const [value,setValue]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <form className="arxiv-import" onSubmit={e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');void request<{doc_id:string}>('/documents/arxiv',{method:'POST',body:JSON.stringify({value}),signal:AbortSignal.timeout(900000)}).then(r=>{setValue('');onImported(r.doc_id);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>arXiv ID 또는 URL<input value={value} onChange={e=>setValue(e.target.value)} placeholder="2603.07952v1 또는 https://arxiv.org/abs/…" maxLength={300} disabled={busy}/></label><button disabled={busy||!value.trim()} type="submit">{busy?<><span className="spinner" aria-hidden="true"/>원문과 그림을 가져오고 있습니다…</>:'arXiv 가져오기'}</button><small>HTML 원문의 표·LaTeX 수식을 우선 사용합니다. HTML이 없으면 PDF를 추출합니다.</small>{error&&<p role="alert">{error}</p>}</form>;
}
