import { useEffect, useRef, useState } from 'react';
import { request } from './api';
import { Icon } from './icons';
export function PdfPreview({docId,pages,onClose,onProcess}:{docId:string;pages:number;onClose:()=>void;onProcess:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);const [page,setPage]=useState(1);const [url,setUrl]=useState('');const [error,setError]=useState('');const [zoom,setZoom]=useState(100);
  useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);
  useEffect(()=>{const controller=new AbortController();setUrl('');setError('');void request<{data_url:string}>(`/documents/${docId}/pages/${page}/image`,{signal:controller.signal}).then(v=>setUrl(v.data_url)).catch(()=>{if(!controller.signal.aborted)setError('원본 페이지를 불러오지 못했습니다.');});return()=>controller.abort();},[docId,page]);
  return <dialog ref={dialog} className="pdf-preview" aria-label="원본 PDF 보기" onCancel={e=>{e.preventDefault();onClose();}}><header><div><b>원본 PDF</b><small>원래 페이지 배치를 그대로 표시합니다.</small></div><button className="icon-button" onClick={onClose} aria-label="원본 PDF 닫기"><Icon name="close"/></button></header><div className="pdf-preview-tools"><button className="icon-button" disabled={page===1} onClick={()=>setPage(p=>p-1)} aria-label="이전 페이지"><Icon name="chevronLeft"/></button><label>페이지<input type="number" min={1} max={pages} value={page} onChange={e=>setPage(Math.max(1,Math.min(pages,Number(e.target.value)||1)))}/></label><span>/ {pages}</span><button className="icon-button" disabled={page===pages} onClick={()=>setPage(p=>p+1)} aria-label="다음 페이지"><Icon name="chevronRight"/></button><select aria-label="PDF 확대" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={100}>폭 맞춤</option><option value={150}>150%</option><option value={200}>200%</option></select></div><div className="pdf-page-viewport" tabIndex={0} role="region" aria-label="PDF 페이지 스크롤">{url?<img alt={`원본 PDF ${page}쪽`} src={url} style={{width:`${zoom}%`,maxWidth:'none'}}/>:<p role="status">{error||'페이지를 불러오는 중…'}</p>}</div><footer><button onClick={onClose}>추출 텍스트 보기</button><button className="primary-button" onClick={()=>{onClose();onProcess();}}>AI 리더 만들기</button></footer></dialog>;
}
