import { useEffect, useRef, useState } from 'react';
import { Inline, NOTE_NAMES } from './blocks';
import { BrandMark, Icon } from './icons';
import { resolveTheme } from './theme';
import type { NoteKind, View } from './types';
import './tutorial.css';

type Destination = 'connection' | 'library' | 'settings';
type Scene = { id:string; label:string; title:string; intro:string; where:string; steps:string[]; success:string; tip:string; action:Destination; actionLabel:string };
export const SCENES:Scene[] = [
  {id:'connect',label:'AI 연결',title:'먼저, AI와 연결해요.',intro:'기본은 Anthropic API 키입니다. 이미 로그인한 공식 CLI가 있다면 그 연결도 사용할 수 있어요.',where:'서재 → AI 연결 설정',steps:['API 키 방식: 제공자의 개발자 콘솔에서 API 키를 준비합니다. Anthropic이 기본이며 OpenAI·Google AI Studio도 선택할 수 있습니다.','제공자와 연결 방식을 선택하고 키를 입력한 뒤 ‘키 저장’ → ‘연결 확인’을 누릅니다.','공식 CLI 방식: Claude Code 또는 Codex를 별도로 설치하고 터미널에서 직접 로그인합니다. 앱에서 해당 제공자와 ‘내 구독 · 공식 CLI’를 고른 뒤 ‘연결 확인’을 누릅니다.'],success:'‘연결 확인 완료 · 기본 번역 연결로 설정했습니다.’라는 문구가 보이면 준비 끝입니다.',tip:'API 요금은 구독과 별도입니다. 키는 Windows 자격 증명 관리자에만 저장됩니다. 연결 확인에서는 논문을 보내지 않으며 번역·질문을 시작할 때 전송합니다.',action:'connection',actionLabel:'실제 AI 연결 설정 열기'},
  {id:'import',label:'논문 가져오기',title:'읽고 싶은 논문을 가져와요.',intro:'PDF 파일을 놓거나 arXiv 주소를 입력하세요.',where:'서재 → PDF 파일 선택 / arXiv 가져오기',steps:['PDF를 업로드 영역에 끌어 놓거나 ‘PDF 파일 선택’을 누릅니다. 최대 150MB까지 지원합니다.','arXiv는 ‘2603.07952v1’ 같은 ID 또는 논문 URL을 입력합니다. HTML이 있으면 표·LaTeX 수식을 우선 가져오고, 없으면 PDF를 추출합니다.','가져오기가 끝나면 ‘원문·대역 읽기’로 열어 봅니다. AI 처리 전 PDF는 원본 페이지로, arXiv HTML은 구조화된 원문으로 시작합니다.'],success:'논문이 서재에 나타나고 원문을 열 수 있으면 가져오기가 끝났습니다.',tip:'‘추출 텍스트 보기’는 자동 추출 미리보기입니다. 아직 번역을 만들지 않았다면 원문만 보이는 것이 정상입니다. arXiv 그림 다운로드에는 수 분 걸릴 수 있어요.',action:'library',actionLabel:'서재에서 논문 가져오기'},
  {id:'translate',label:'번역 시작',title:'사용량을 확인하고 번역해요.',intro:'한 번에 원문 복원, 용어집, 한국어 번역, 맥락 주석을 만듭니다. 시작 전에 연결과 모델을 확인하세요.',where:'서재 → 처리 상태 → 번역·주석 시작',steps:['‘처리 상태’를 열고 예상 입력·출력 토큰과 단계별 모델을 확인합니다. 예상치는 실제 비용이나 사용량과 다를 수 있습니다.','‘번역·주석 시작’을 누릅니다. 본문과 표·수식 복원용 이미지가 선택한 AI 제공자에게 전송됩니다.','진행 창을 닫아도 처리는 계속됩니다. 멈추려면 ‘일시정지’, 다시 시작하려면 ‘이어서 실행’을 누릅니다.'],success:'‘완료’ 또는 ‘검수 필요’ 상태가 되면 리더에서 번역과 주석을 확인합니다.',tip:'번역 언어는 한국어이며 참고문헌은 원문을 유지합니다. 앱을 종료했다면 다음 실행에서 ‘처리 상태’를 열어 저장된 단계부터 이어서 실행하세요.',action:'library',actionLabel:'서재에서 처리 상태 확인'},
  {id:'read',label:'대역 리더',title:'나에게 맞는 방식으로 읽어요.',intro:'원문과 번역을 나란히 비교하거나 한 언어에 집중하세요. 읽던 위치와 보기 설정도 저장됩니다.',where:'리더 상단 도구 모음 · 왼쪽 목차',steps:['상단의 ‘원문 / 대역 / 번역’으로 보기를 바꿉니다. Ctrl+1 / 2 / 3으로도 전환할 수 있습니다.','목차를 눌러 섹션으로 이동합니다. 좁은 창에서는 ☰ 버튼으로 목차를 엽니다. 상단 바와 하단의 %로 읽기 진행률을 확인합니다.','Ctrl+F로 원문·번역을 검색하고 A− / A+로 글자 크기, 테마 버튼으로 라이트·다크 테마를 바꿉니다.'],success:'보기 모드를 바꿔도 같은 문단을 읽고, 앱을 다시 열어 읽던 위치로 돌아올 수 있습니다.',tip:'아직 번역되지 않은 블록은 원문을 표시합니다. 좁은 창의 대역 모드는 원문과 번역이 위아래로 이어집니다.',action:'library',actionLabel:'서재에서 논문 열어 읽기'},
  {id:'original',label:'표·수식·그림',title:'중요한 수치는 원본과 함께.',intro:'표는 표 안에서 가로로 움직이고, 그림은 크게 열어 봅니다. 수식의 LaTeX 원문도 확인할 수 있어요.',where:'리더의 표·수식·그림 · 원본 PDF 보기',steps:['넓은 표는 표 영역 안에서 가로로 스크롤합니다. 행·열 제목과 병합 셀을 함께 보며 수치를 읽습니다.','그림의 ‘확대 보기’를 누르고 + / − 또는 ‘화면 맞춤’으로 확인합니다. 원본 이미지가 있는 문서에서 사용할 수 있습니다.','수식의 ‘LaTeX 원문’을 펼치거나 ‘LaTeX 복사’를 누릅니다. 실제 PDF 문서는 ‘원본 PDF 보기’에서 페이지 배치와 비교할 수 있습니다.'],success:'핵심 표의 수치·행/열 제목과 수식 기호가 원본과 같은지 확인합니다.',tip:'파서와 AI 복원에는 오류가 있을 수 있습니다. 표·그림·수식이 이상하면 원본과 비교하고 다음 설명의 검수 기능을 사용하세요.',action:'library',actionLabel:'서재에서 논문의 표·수식 보기'},
  {id:'ask',label:'Ask AI',title:'막힌 문장에서 바로 질문해요.',intro:'문장을 선택하면 해당 문맥을 바탕으로 대화할 수 있습니다. 표·그림 참조와 주변 문단도 함께 확인하세요.',where:'문장 선택 → Ask AI / Ctrl+K',steps:['문장을 드래그한 뒤 ‘Ask AI’를 누르거나 Ctrl+K를 누릅니다. 블록 옆 Ask AI 버튼은 블록 전체를 대상으로 합니다.','‘쉽게 설명’, ‘3문장 요약’ 같은 프리셋 또는 직접 쓴 질문을 보냅니다. 전송 전에 제공자·모델과 ‘논문 전체 포함’ 여부, 예상 사용량을 확인합니다.','같은 대화에서 후속 질문을 이어갑니다. ‘전송 컨텍스트 확인’으로 사용된 문맥을 보고, 좋은 답변은 복사·‘주석으로 저장’·‘발표 노트에 추가’합니다.'],success:'선택한 문장과 답변이 같은 패널에 보이고, 말풍선 배지로 이전 대화를 다시 열 수 있습니다.',tip:'‘질문 규칙·프리셋’에서 지시와 질문 템플릿을 바꿀 수 있습니다. Codex CLI는 작성 중 표시 후 완성된 메시지를 보여줍니다.',action:'library',actionLabel:'서재에서 논문 열고 질문하기'},
  {id:'review',label:'주석·검수',title:'AI의 설명도 근거를 확인해요.',intro:'색은 주석의 종류를, 근거 링크는 돌아가 볼 원문을 알려줍니다. 검수 표시는 확인이 필요한 부분입니다.',where:'목차의 주석 필터 · 검수할 블록 보기',steps:['목차에서 주석 표시·종류·밀도를 조절합니다. 핵심, 결과, 한계, 해석, 수식, 용어의 6가지 색을 사용할 수 있습니다.','주석의 ‘논문 명시 / 해석 / 혼합’과 근거 링크를 확인합니다. ‘검수할 블록 보기’로 누락·숫자·용어 확인이 필요한 곳으로 이동합니다.','내 논문에서 ‘번역 수정’ 또는 ‘주석 수정·재생성’을 펼쳐 직접 수정하고 저장합니다. 필요하면 블록 재번역·주석 재생성·수식 복원을 다시 요청합니다.'],success:'원문 근거와 비교해 내용을 확인하고, 수정한 내용이 다시 열어도 유지되면 됩니다.',tip:'자동 검증 통과가 주장의 사실 여부를 보증하지는 않습니다. AI 재생성에는 사용량이 발생합니다. 직접 입력해 수정 저장하는 작업은 AI를 호출하지 않습니다.',action:'library',actionLabel:'서재에서 논문의 주석 살펴보기'},
  {id:'summary',label:'요약·흐름',title:'논문 전체를 한눈에 정리해요.',intro:'섹션마다 핵심을 정리한 뒤 문제 → 기존 한계 → 제안 방법 → 핵심 결과 → 한계로 묶고, 섹션이 이어지는 흐름과 핵심 그림·표를 보여 줍니다.',where:'리더 → 요약 탭 → 요약 만들기',steps:['리더 위쪽 소개 영역 아래에서 ‘요약’ 탭을 누릅니다. 예상 AI 호출 수와 토큰을 확인하고 ‘요약 만들기’를 누릅니다.','근거 칩(예: Table 1)을 누르면 본문의 해당 위치로 이동합니다. 요약 속 숫자를 근거에서 찾지 못한 항목에는 ‘근거 확인 필요’가 붙습니다.','항목마다 ‘고치기’로 직접 다듬고, ‘발표 노트에 추가’나 ‘AI에게 질문’으로 이어 갈 수 있습니다.'],success:'요약 탭에서 논문의 문제와 결과, 섹션이 이어지는 흐름을 보고 원문 근거로 바로 오갈 수 있습니다.',tip:'요약은 번역 전에도 만들 수 있고, 한 번 만들면 저장됩니다. ‘다시 만들기’는 직접 고친 내용을 덮어쓰니 확인 후 진행하세요.',action:'library',actionLabel:'서재에서 논문 요약해 보기'},
  {id:'present',label:'발표 노트',title:'이해한 내용을 발표 흐름으로.',intro:'유용한 AI 답변과 논문 블록을 모으고 내 설명을 더해 발표 순서를 정리합니다.',where:'AI 답변 → 발표 노트에 추가 / 리더 → 발표 노트',steps:['완성된 AI 답변에서 ‘발표 노트에 추가’를 누릅니다. 리더 상단의 ‘발표 노트’에서 모은 내용을 엽니다.','‘논문 블록에서 가져오기’로 원문 근거를 더하거나 ‘새 메모 작성’으로 직접 씁니다. 제목·내용을 편집하고 ‘메모 저장’을 누릅니다.','↑ / ↓로 순서를 바꾸고 ‘발표 노트 내보내기’로 Markdown 파일을 저장합니다.'],success:'모아 둔 메모를 원하는 순서로 읽을 수 있고, 앱을 다시 열어도 남아 있습니다.',tip:'발표 노트는 슬라이드 파일이 아닌 Markdown 메모입니다. 발표 전에 수치와 인용을 원문에서 확인하고, 편집한 내용은 ‘메모 저장’을 누르세요.',action:'library',actionLabel:'서재에서 발표 노트 써 보기'},
  {id:'export',label:'내보내기',title:'앱 밖에서도 논문을 읽어요.',intro:'원문·번역·주석을 파일로 저장합니다. HTML은 인터넷 연결 없이 읽을 수 있는 독립 리더입니다.',where:'리더 → 내보내기 → 저장 위치 선택',steps:['‘단일 HTML · 오프라인 리더’를 선택하면 글꼴·그림·수식·리더 기능이 파일 하나에 들어갑니다.','편집할 문서가 필요하면 ‘Markdown 대역본’, 발표용 메모만 필요하면 ‘발표 노트 Markdown’을 고릅니다.','‘저장 위치 선택’으로 저장한 뒤 파일을 열어 봅니다. HTML은 앱을 닫고 인터넷을 끈 상태에서도 읽어볼 수 있습니다.'],success:'HTML에서 원문/대역/번역, 목차·검색·다크모드가 동작하고 표·그림·수식이 보입니다.',tip:'내보내기는 AI 호출 없이 현재 저장된 내용을 담습니다. HTML에서 AI 질문·편집은 제공하지 않습니다. Markdown 표·수식 지원은 뷰어마다 다르며 공유 시 원문의 이용 조건을 확인하세요.',action:'library',actionLabel:'서재에서 논문 내보내기'},
  {id:'settings',label:'저장·문제 해결',title:'계속 사용할 준비가 됐어요.',intro:'데이터 위치와 업데이트는 앱 설정에서 관리합니다. 막혔을 때 돌아올 곳도 기억해 두세요.',where:'서재 → 앱 설정',steps:['저장 위치를 바꾸려면 ‘새 저장 폴더 선택’에서 빈 폴더를 고른 뒤 ‘복사·검증 후 재시작’을 누릅니다. 번역·질문·가져오기가 끝난 뒤 진행하세요.','논문·번역·대화·발표 노트를 복사·검증하며 기존 폴더는 보존합니다. API 키는 Windows 자격 증명 관리자에 남습니다.','업데이트 배포 경로가 연결된 빌드는 새 버전을 확인할 수 있습니다. 미설정이라고 나오면 새 설치 파일로 업데이트합니다.'],success:'원본 읽기 → AI 번역 → 확인·질문 → 발표 노트·내보내기의 흐름을 직접 사용할 수 있습니다.',tip:'연결 실패는 AI 연결 설정, 처리 중단은 처리 상태, 레이아웃 문제는 원본 PDF 보기부터 확인하세요. 문제를 알려줄 때 논문 파일명·한 행동·이상한 결과를 함께 기록하면 좋습니다.',action:'settings',actionLabel:'실제 앱 설정 열기'},
];
const PROGRESS_KEY='paperduet-tutorial-v1';
const validScene=(id:string)=>SCENES.some(s=>s.id===id);
function loadProgress():{last:string;done:string[]}{
  try{const saved=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');return {last:validScene(saved?.last)?saved.last:'connect',done:Array.isArray(saved?.done)?saved.done.filter((id:unknown)=>typeof id==='string'&&validScene(id)):[]};}catch{return {last:'connect',done:[]};}
}
export const lastTutorialScene=()=>loadProgress().last;

export function Tutorial({sceneId,onScene,onGo}:{sceneId:string;onScene:(id:string)=>void;onGo:(target:Destination)=>void}){
  // Builds without the bundled sample send sample shortcuts to the library instead.
  const index=Math.max(0,SCENES.findIndex(s=>s.id===sceneId));const scene=SCENES[index];
  const [done,setDone]=useState(loadProgress().done);
  const [theme,setTheme]=useState(resolveTheme(document.documentElement.dataset.theme));
  const title=useRef<HTMLHeadingElement>(null);const mounted=useRef(false);
  useEffect(()=>{const previous=document.documentElement.dataset.theme;return()=>{if(previous)document.documentElement.dataset.theme=previous;else delete document.documentElement.dataset.theme;};},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({last:scene.id,done}));}catch{/* Reading the guide works even without local storage. */}},[scene.id,done]);
  useEffect(()=>{if(mounted.current){title.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}mounted.current=true;},[scene.id]);
  const markDone=()=>setDone(values=>values.includes(scene.id)?values:[...values,scene.id]);
  return <div className="tutorial-page">
    <a className="skip-link" href="#tutorial-scene-title">본문으로 이동</a>
    <header className="tutorial-header"><a className="brand" href="?library=1" onClick={e=>{e.preventDefault();onGo('library');}}><BrandMark/><b>PaperDuet</b><span className="tutorial-header-label">사용 가이드</span></a><div><button aria-label="가이드 테마 변경" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☾ 다크':'☀ 라이트'}</button><button onClick={()=>onGo('library')}>서재로</button></div></header>
    <div className="tutorial-layout"><aside className="tutorial-sidebar"><div className="eyebrow">Get to know PaperDuet</div><h1>어려운 영어 논문을<br/>한국어로 이해해보세요.</h1><div className="tutorial-completion"><span>확인한 설명 <b>{done.length} / {SCENES.length}</b></span><progress aria-label="가이드 완료 진행률" max={SCENES.length} value={done.length}/></div><nav aria-label="가이드 설명">{SCENES.map((s,i)=><button key={s.id} aria-current={s.id===scene.id?'step':undefined} onClick={()=>onScene(s.id)}><span className="tutorial-step-number">{String(i+1).padStart(2,'0')}</span><span>{s.label}</span>{done.includes(s.id)&&<span className="tutorial-tick" aria-label="확인 완료">✓</span>}</button>)}</nav><div className="tutorial-sidebar-note">가이드는 설명용 예시입니다.<br/>실제 AI를 호출하거나<br/>논문 데이터를 바꾸지 않습니다.</div></aside>
      <main className="tutorial-main"><div className="tutorial-mobile-index"><label>설명 선택<select value={scene.id} onChange={e=>onScene(e.target.value)}>{SCENES.map((s,i)=><option key={s.id} value={s.id}>{i+1}. {s.label}{done.includes(s.id)?' ✓':''}</option>)}</select></label><span>{done.length}/10 확인</span></div>
        <div className="tutorial-scene-intro"><span className="eyebrow">설명 {String(index+1).padStart(2,'0')} / {SCENES.length}</span><h2 id="tutorial-scene-title" ref={title} tabIndex={-1}>{scene.title}</h2><p>{scene.intro}</p><div className="tutorial-location"><span>찾아가기</span>{scene.where}</div></div>
        <section className="tutorial-preview" aria-label={`${scene.label} 화면 예시`}><div className="tutorial-preview-bar"><span className="tutorial-window-dots" aria-hidden="true">● ● ●</span><span>PaperDuet · {scene.label}</span><span>설명용 예시</span></div><ScenePreview key={scene.id} id={scene.id}/></section>
        <div className="tutorial-instructions"><section aria-labelledby="tutorial-follow-title"><h3 id="tutorial-follow-title">이렇게 따라 해보세요</h3><ol>{scene.steps.map((step,i)=><li key={step}><span>{i+1}</span><p>{step}</p></li>)}</ol></section><aside className="tutorial-check"><span>✓ 이 설명을 마치면</span><p>{scene.success}</p><button onClick={()=>onGo(scene.action)}>{scene.actionLabel} ↗</button></aside></div>
        <div className="tutorial-tip"><b>알아두면 좋아요</b><p>{scene.tip}</p></div>
        {scene.id==='settings'&&<section className="tutorial-shortcuts"><h3>손에 익혀 두면 편한 단축키</h3><dl>{[['Ctrl + 1 / 2 / 3','원문 / 대역 / 번역'],['Ctrl + F','문서 검색'],['Ctrl + K','선택한 문장에 질문'],['Esc','열린 대화상자 닫기']].map(([key,value])=><div key={key}><dt><kbd>{key}</kbd></dt><dd>{value}</dd></div>)}</dl></section>}
        <footer className="tutorial-navigation"><button disabled={index===0} onClick={()=>onScene(SCENES[index-1].id)}>← 이전 설명</button><button className="tutorial-mark" aria-pressed={done.includes(scene.id)} onClick={()=>setDone(values=>values.includes(scene.id)?values.filter(id=>id!==scene.id):[...values,scene.id])}>{done.includes(scene.id)?'✓ 확인 완료':'이 설명 확인했어요'}</button>{index<SCENES.length-1?<button className="primary-button" onClick={()=>{markDone();onScene(SCENES[index+1].id);}}>다음 설명 →</button>:<button className="primary-button" onClick={()=>{markDone();onGo('library');}}>서재로 시작하기 →</button>}</footer>
        <p className="tutorial-endnote">언제든 서재의 ‘사용 가이드’ 또는 리더의 ? 버튼으로 돌아올 수 있어요.</p>
      </main></div>
  </div>;
}

function DemoButton({children,primary=false}:{children:React.ReactNode;primary?:boolean}){return <span className={`tutorial-demo-button ${primary?'demo-primary':''}`}>{children}</span>;}
function DemoField({label,children}:{label:string;children:React.ReactNode}){return <div className="tutorial-demo-field"><span>{label}</span><div>{children}</div></div>;}
function ScenePreview({id}:{id:string}){
  const [mode,setMode]=useState<'api'|'claude'|'codex'>('api');
  const [view,setView]=useState<View>('split');
  const [kind,setKind]=useState<NoteKind>('key');
  const [format,setFormat]=useState('html');
  const [reordered,setReordered]=useState(false);
  const [question,setQuestion]=useState('쉽게 설명');
  if(id==='connect')return <div className="tutorial-demo tutorial-connect"><div className="tutorial-demo-tabs" role="group" aria-label="연결 예시 선택">{([['api','API 키'],['claude','Claude CLI'],['codex','Codex CLI']] as const).map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div><div className="tutorial-demo-card"><h3>AI 연결 설정</h3><div className="tutorial-demo-fields"><DemoField label="제공자">{mode==='codex'?'OpenAI':'Anthropic'} <span>⌄</span></DemoField><DemoField label="연결 방식">{mode==='api'?'API 키':'내 구독 · 공식 CLI'} <span>⌄</span></DemoField></div>{mode==='api'?<><DemoField label="API 키 · 실제 키를 입력하는 곳은 설정 화면입니다">••••••••••••••••••••••••</DemoField><div className="tutorial-demo-actions"><DemoButton primary>1 · 키 저장</DemoButton><DemoButton>2 · 연결 확인</DemoButton></div></>:<><p>터미널에서 직접 로그인한 뒤 앱으로 돌아오세요.</p><pre className="tutorial-command">{mode==='claude'?'claude auth login':'codex login'}</pre><DemoField label="CLI 실행 파일 경로">자동 탐지 시 비워 두기</DemoField><DemoButton primary>연결 확인</DemoButton></>}<div className="tutorial-demo-success"><span>✓</span> 연결 확인 완료 · 기본 번역 연결로 설정했습니다.<small>연결에 성공했을 때의 예시 상태입니다.</small></div></div></div>;
  if(id==='import')return <div className="tutorial-demo tutorial-import"><div className="tutorial-demo-drop"><span><Icon name="upload"/></span><h3>PDF를 여기에 놓으세요</h3><p>최대 150MB · 원본은 이 PC에 저장됩니다.</p><DemoButton primary>PDF 파일 선택</DemoButton></div><div className="tutorial-import-divider">또는</div><div className="tutorial-demo-card"><DemoField label="arXiv ID 또는 URL">2603.07952v1</DemoField><DemoButton>arXiv 가져오기</DemoButton><p className="tutorial-caption">HTML의 표·수식 우선 → 없으면 PDF 추출</p></div></div>;
  if(id==='translate')return <div className="tutorial-demo tutorial-process"><div><span className="tutorial-demo-badge">시작 전 확인</span><h3>논문 처리</h3><div className="tutorial-demo-steps">{['원문 추출','구조 정리','표·수식 복원','용어집','전문 번역','맥락 주석','검증'].map((label,i)=><div key={label} className={i===4?'current':''}><span>{i<2?'✓':String(i+1).padStart(2,'0')}</span>{label}</div>)}</div></div><div className="tutorial-demo-card"><h4>예상 사용량</h4><p>입력·출력 토큰 확인</p><div className="tutorial-demo-rule"/><p>제공자 · 연결 방식<br/>복원 / 용어집 / 번역 / 주석 모델</p><DemoButton primary>번역·주석 시작</DemoButton><small>실제 처리 화면에서 누르면 AI 전송이 시작됩니다.</small></div></div>;
  if(id==='read')return <div className="tutorial-demo"><div className="tutorial-demo-toolbar"><div className="tutorial-demo-tabs" role="group" aria-label="리더 보기 예시">{([['en','원문'],['split','대역'],['ko','번역']] as const).map(([v,label])=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{label}</button>)}</div><span>⌕　A−　A+　◐</span></div><div className="tutorial-mini-reader"><div className="tutorial-mini-toc"><b>Contents</b><span>Abstract</span><strong>1 Introduction</strong><span>2 Method</span><span>3 Experiments</span></div><div className="tutorial-mini-paper"><span className="tutorial-demo-badge">1 Introduction</span><h3>Detect Anything via<br/>Next Point Prediction</h3><div className={`tutorial-parallel tutorial-view-${view}`}>{view!=='ko'&&<p lang="en">The model predicts the next point.<br/><br/>Read the original text and compare it with the Korean translation.</p>}{view!=='en'&&<p lang="ko">모델은 다음 점을 예측합니다.<br/><br/>원문을 읽고 한국어 번역과 비교해 보세요.</p>}</div><div className="tutorial-mini-progress"><span/></div><small>보기 버튼을 눌러 예시를 바꿔 보세요.</small></div></div></div>;
  if(id==='original')return <div className="tutorial-demo tutorial-original"><div className="tutorial-demo-card"><span className="tutorial-demo-badge">Table · 가로 스크롤</span><div className="tutorial-example-table" tabIndex={0} role="region" aria-label="예시 표 가로 스크롤"><table><caption>조작 설명용 표 · 실제 논문 수치가 아닙니다</caption><thead><tr><th>Method</th>{['Metric A','Metric B','Metric C','Metric D','Metric E'].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{['Baseline','Proposed'].map((n,i)=><tr key={n}><td>{n}</td>{[1,2,3,4,5].map(k=><td key={k}>{(40+i*2+k/10).toFixed(1)}</td>)}</tr>)}</tbody></table></div><p className="tutorial-caption">↔ 표 안을 좌우로 움직여 보세요.</p></div><div className="tutorial-demo-card tutorial-mini-equation"><span className="tutorial-demo-badge">Equation · 원문 대조</span><Inline text={String.raw`\(\mathrm{Precision}=\frac{TP}{TP+FP}\)`}/><div className="tutorial-demo-actions"><DemoButton>LaTeX 원문</DemoButton><DemoButton>LaTeX 복사</DemoButton></div><p className="tutorial-caption">그림: 확대 보기 → + / − → 화면 맞춤</p></div></div>;
  if(id==='ask')return <div className="tutorial-demo tutorial-ask"><div className="tutorial-ask-selection"><span className="tutorial-demo-badge">선택한 문장</span><p>The model <mark>predicts the next point</mark> to represent an object.</p><div className="tutorial-demo-actions"><DemoButton primary>Ask AI</DemoButton><kbd>Ctrl + K</kbd></div></div><div className="tutorial-demo-card"><h3>Ask AI <small>예시 대화</small></h3><div className="tutorial-demo-tabs" role="group" aria-label="질문 프리셋 예시">{['쉽게 설명','3문장 요약','발표용 문구'].map(q=><button key={q} aria-pressed={question===q} onClick={()=>setQuestion(q)}>{q}</button>)}</div><p className="tutorial-example-answer">{question==='쉽게 설명'?'물체의 위치를 나타내는 다음 점을 하나씩 예측한다고 이해하면 됩니다.':question==='3문장 요약'?'물체를 점으로 표현합니다. 모델은 다음 점을 예측합니다. 구체적인 학습 방법과 결과는 원문에서 확인합니다.':'한 줄 예시: “다음 점 예측으로 물체의 위치를 표현합니다.”'}</p><div className="tutorial-demo-actions"><DemoButton>주석으로 저장</DemoButton><DemoButton>발표 노트에 추가</DemoButton></div><small>이 답변은 가이드용 예시이며 AI를 호출하지 않습니다.</small></div></div>;
  if(id==='review')return <div className="tutorial-demo"><div className="tutorial-demo-tabs tutorial-note-tabs" role="group" aria-label="주석 종류 예시">{(Object.entries(NOTE_NAMES) as [NoteKind,string][]).map(([value,label])=><button className={`n-${value}`} key={value} aria-pressed={kind===value} onClick={()=>setKind(value)}>{label}</button>)}</div><div className={`tutorial-note n-${kind}`}><div><span>{NOTE_NAMES[kind]}</span><strong>{{key:'핵심 아이디어를 한눈에',res:'결과와 수치를 확인하기',lim:'성립하지 않는 조건도 읽기',ins:'논문 명시와 해석 구분하기',mth:'수식의 기호와 의미 이해하기',trm:'처음 만나는 용어 설명'}[kind]}</strong></div><p>{{key:'논문의 핵심을 짚어 주는 주석입니다. 설명과 함께 연결된 원문 근거를 읽어보세요.',res:'수치만 보지 말고 어떤 데이터와 조건에서 나온 결과인지 함께 확인합니다.',lim:'평가 범위, 데이터, 가정에 따른 한계를 확인합니다.',ins:'AI가 덧붙인 해석인지, 논문에 명시된 주장인지 구분합니다.',mth:'기호의 정의, 연산의 의미, 논문에서 왜 사용하는지를 함께 봅니다.',trm:'이 문맥에서 쓰인 전문 용어의 뜻과 번역을 확인합니다.'}[kind]}</p><footer>주장 유형: 해석 <span>근거 → 본문 블록</span></footer></div><div className="tutorial-demo-card tutorial-review-row"><span>검수 필요 · 주석 숫자·근거 확인</span><DemoButton>수정 저장</DemoButton><DemoButton>이 주석 재생성</DemoButton></div></div>;
  if(id==='summary')return <div className="tutorial-demo"><div className="tutorial-demo-card"><span className="tutorial-demo-badge">요약 탭</span><h3>구조화 요약</h3><div className="tutorial-demo-note-list">{[['문제','풀려는 질문과 그 중요성'],['제안 방법','핵심 아이디어와 작동 방식'],['핵심 결과','근거 표·그림으로 이동']].map(([n,s],i)=><div key={n}><span>0{i+1}</span><strong>{n}</strong><small>{s}</small></div>)}</div><div className="tutorial-demo-rule"/><DemoField label="섹션 흐름">서론 → 방법 → 실험 → 결론</DemoField><div className="tutorial-demo-actions"><DemoButton primary>요약 만들기</DemoButton><DemoButton>근거로 이동</DemoButton></div></div></div>;
  if(id==='present')return <div className="tutorial-demo"><div className="tutorial-demo-card"><h3>발표 노트</h3><div className="tutorial-demo-note-list">{(reordered?['핵심 방법','연구 질문']:['연구 질문','핵심 방법']).map((n,i)=><div key={n}><span>0{i+1}</span><strong>{n}</strong><small>근거 블록 포함</small></div>)}</div><button onClick={()=>setReordered(!reordered)}>↑ ↓ 예시 순서 바꾸기</button><div className="tutorial-demo-rule"/><DemoField label="메모 제목">나의 발표 핵심</DemoField><div className="tutorial-demo-note-body">논문이 풀려는 문제 → 제안한 방법 → 결과 → 한계<br/><small>원문 근거에 내가 이해한 설명을 더합니다.</small></div><div className="tutorial-demo-actions"><DemoButton primary>메모 저장</DemoButton><DemoButton>발표 노트 내보내기</DemoButton></div></div></div>;
  if(id==='export')return <div className="tutorial-demo tutorial-export"><div className="tutorial-demo-card"><h3>논문 내보내기</h3><label>파일 형식<select aria-label="내보내기 형식 예시" value={format} onChange={e=>setFormat(e.target.value)}><option value="html">단일 HTML · 오프라인 리더</option><option value="md">Markdown 대역본</option><option value="presentation">발표 노트 Markdown</option></select></label><DemoButton primary>저장 위치 선택</DemoButton></div><div className="tutorial-export-file"><span aria-hidden="true">{format==='html'?'↔':'≡'}</span><b>{format==='html'?'paper.html':format==='md'?'paper.md':'presentation.md'}</b><p>{format==='html'?'원문·번역·주석 + 리더\n글꼴·그림·수식 모두 내장':format==='md'?'원문과 번역을 함께\n병합 표 · LaTeX · 내장 이미지':'모아 둔 메모를\n현재 발표 순서대로'}</p><small>내보내기에는 AI 호출이 없습니다.</small></div></div>;
  return <div className="tutorial-demo"><div className="tutorial-demo-card"><h3>앱 설정</h3><h4>저장 위치</h4><div className="tutorial-storage-flow"><span>현재 폴더<br/><b>그대로 보관</b></span><span aria-hidden="true">→</span><span>새 빈 폴더<br/><b>복사 · 검증</b></span></div><div className="tutorial-demo-actions"><DemoButton>새 저장 폴더 선택</DemoButton><DemoButton primary>복사·검증 후 재시작</DemoButton></div><div className="tutorial-demo-rule"/><h4>업데이트</h4><p>현재 로컬 빌드: 배포 경로 미설정<br/><small>새 설치 파일로 업데이트할 수 있습니다.</small></p></div></div>;
}
